spring.application.name=pay_guard_bkd
spring.jpa.hibernate.ddl-auto=update
spring.datasource.name=Password5*
spring.datasource.password=rootuser
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
