spring.application.name=pay_guard_bkd

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}?sslmode=require
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


payguard.fraud.thresholds.approve=30
payguard.fraud.thresholds.review=80
payguard.fraud.thresholds.decline=120

payguard.fraud.high-amount.limit=500000

payguard.fraud.rate-limit.max-requests=5
payguard.fraud.rate-limit.window-minutes=1

payguard.fraud.velocity.max-transactions=5
payguard.fraud.velocity.window-minutes=10
