spring.application.name=pay_guard_bkd
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=rootuser
spring.datasource.password=Password5*
spring.datasource.url=jdbc:postgresql://localhost:5432/pay_guard
